# Generated by Django 5.2.8 on 2025-11-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='content',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='title',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='ai_insights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='ai_sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='entry_type',
            field=models.CharField(choices=[('voice', 'Voice'), ('text', 'Text')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='processing_mode',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=15),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
