# Generated by Django 5.2.8 on 2025-11-21 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0003_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('category', models.CharField(choices=[('food', 'Food & Beverages'), ('groceries', 'Groceries'), ('transport', 'Transport'), ('fuel', 'Fuel / Petrol / Diesel'), ('travel', 'Travel & Trips'), ('shopping', 'Shopping'), ('clothing', 'Clothing & Accessories'), ('electronics', 'Electronics'), ('subscriptions', 'Subscriptions'), ('entertainment', 'Entertainment'), ('health', 'Health & Medical'), ('fitness', 'Fitness / Gym'), ('education', 'Education / Courses'), ('books', 'Books & Stationery'), ('utilities', 'Utilities'), ('rent', 'Rent / Accommodation'), ('maintenance', 'Home Maintenance'), ('personal', 'Personal Care'), ('beauty', 'Beauty & Salon'), ('gifts', 'Gifts & Donations'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('business', 'Business Expenses'), ('restaurant', 'Restaurant / Dining'), ('fast_food', 'Fast Food'), ('coffee', 'Coffee / Snacks'), ('pharmacy', 'Pharmacy'), ('mobile', 'Mobile Recharge / Bills'), ('internet', 'Internet / Broadband'), ('parking', 'Parking Charges'), ('car_service', 'Car / Bike Service'), ('ride_sharing', 'Uber / Ola / Taxi'), ('investment', 'Investments'), ('pet', 'Pet Care'), ('kids', 'Kids / Childcare'), ('misc', 'Miscellaneous'), ('other', 'Other')], default='other', max_length=50)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('upi', 'UPI / Wallet'), ('bank', 'Bank Transfer'), ('other', 'Other')], default='upi', max_length=20)),
                ('merchant', models.CharField(blank=True, max_length=100, null=True)),
                ('detected_text', models.TextField(blank=True, default='')),
                ('confidence_score', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diary_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='diary.diaryentry')),
            ],
        ),
    ]
