# Generated by Django 5.2.8 on 2025-11-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_chat_questions_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('trial', 'Trial'), ('premium', 'Premium')], default='free', max_length=10),
        ),
    ]
